name: AWS Docker Push Nextjs App
on: 
  push: 
    branches: [ "main" ]
  
jobs:
  Build-docker-image:
   
  
    name: Build Docker Image and Push
    runs-on: ubuntu-latest  
    steps:  
        - name: Checkout Branch
          uses: actions/checkout@v2    
          
        - name: Setup AWS ECR Details
          uses: aws-actions/configure-aws-credentials@v4
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: ${{secrets.AWS_REGION}}


        - name: Login to Amazon ECR
          id: login-pf-aws-ecr
          uses: aws-actions/amazon-ecr-login@v1
          with:
            mask-password: 'true'
          

        - name: Build and push the tagged docker image to Amazon ECR
          env:
            ECR_REGISTRY: ${{ steps.login-pf-aws-ecr.outputs.registry }}
            ECR_REPOSITORY: "andrew-doser/containers/repository"
            IMAGE_TAG: ${{github.run_number}}
          run: |
            docker build -t ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }} .
            docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
            docker tag ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }} ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
            docker push ${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:latest
